// Source for the stdio shim that direct-process tabs inject into Node-based
// children via NODE_OPTIONS=--require=<shim>. It patches stdout/stderr/stdin so
// piped Node TUIs see TTY-like metadata and the parent console geometry,
// matching the working diagnostics/win-stdio-shim.js prototype.
export const DIRECT_PROCESS_SHIM_SOURCE = `// Auto-generated by Lean Terminal direct-process tabs.
const cols = Number(process.env.LEAN_TERMINAL_DIRECT_COLUMNS || process.env.COLUMNS || 0);
const rows = Number(process.env.LEAN_TERMINAL_DIRECT_ROWS || process.env.LINES || 0);

function patchStream(stream, isInput) {
  if (!stream) return;
  try {
    if (cols > 0) Object.defineProperty(stream, "columns", { configurable: true, get: () => cols });
    if (rows > 0) Object.defineProperty(stream, "rows", { configurable: true, get: () => rows });
    Object.defineProperty(stream, "isTTY", { configurable: true, get: () => true });
    stream.getWindowSize = () => [cols || 80, rows || 24];
    if (isInput && typeof stream.setRawMode !== "function") {
      stream.setRawMode = () => stream;
    }
  } catch {
    // Best-effort shim; ignore failures.
  }
}

patchStream(process.stdout, false);
patchStream(process.stderr, false);
patchStream(process.stdin, true);
`;

interface FsLike {
  existsSync(path: string): boolean;
  readFileSync(path: string, encoding: string): string;
  writeFileSync(path: string, data: string, encoding: string): void;
  mkdirSync(path: string, options?: { recursive?: boolean }): void;
}

interface PathLike {
  join(...parts: string[]): string;
  dirname(p: string): string;
}

/**
 * Materializes the shim into pluginDir and returns its absolute path.
 * Idempotent: only rewrites if the on-disk content differs.
 */
export function ensureDirectProcessShim(
  pluginDir: string,
  fs: FsLike,
  path: PathLike
): string {
  const target = path.join(pluginDir, "direct-process-shim.js");
  let needsWrite = true;
  try {
    if (fs.existsSync(target)) {
      const current = fs.readFileSync(target, "utf-8");
      needsWrite = current !== DIRECT_PROCESS_SHIM_SOURCE;
    }
  } catch {
    needsWrite = true;
  }

  if (needsWrite) {
    try {
      fs.mkdirSync(path.dirname(target), { recursive: true });
    } catch {
      // ignore
    }
    fs.writeFileSync(target, DIRECT_PROCESS_SHIM_SOURCE, "utf-8");
  }

  return target;
}
